name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-24.04
          # - target: x86_64-unknown-linux-gnu
          #   os: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    name: build-${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: build-${{ matrix.os }}
        run: |
          bash build.sh ${{ matrix.target }} ${{ matrix.os }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mpv-${{ matrix.os }}-deb
          path: ./mpv-${{ matrix.os }}.deb
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mpv-${{ matrix.os }}-tar-gz
          path: ./mpv-${{ matrix.os }}.tar.gz
  release:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: mpv
          pattern: mpv*
          merge-multiple: true

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: ncipollo/release-action@v1
        with:
          artifacts: "mpv/*"
          allowUpdates: true